// Generated by CoffeeScript 1.6.3
var Opponent1, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Opponent1 = (function(_super) {
  __extends(Opponent1, _super);

  function Opponent1() {
    _ref = Opponent1.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  return Opponent1;

})(Player);
