// Generated by CoffeeScript 1.6.3
var Opponent1,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Opponent1 = (function(_super) {
  __extends(Opponent1, _super);

  function Opponent1() {
    var card, _i, _len, _ref;
    this.cards = [];
    this.cards.push(new Card_Red_XIII_1(this));
    this.cards.push(new Card_Jecht_1(this));
    this.deck = new Deck(this);
    _ref = this.cards;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      card = _ref[_i];
      this.deck.add(card);
    }
  }

  return Opponent1;

})(Player);
