// Generated by CoffeeScript 1.6.3
var Card_Chaos, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Card_Chaos = (function(_super) {
  __extends(Card_Chaos, _super);

  function Card_Chaos() {
    _ref = Card_Chaos.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Card_Chaos.prototype.name = 'Red XIII';

  Card_Chaos.prototype.cost = {
    fire: 3
  };

  Card_Chaos.prototype.position = 'forward';

  Card_Chaos.prototype.title = 'Warrior';

  Card_Chaos.prototype.serial = '1-023R';

  Card_Chaos.prototype.power = 7000;

  Card_Chaos.prototype.passives = [
    {
      text: 'When Red XIII enters the Field, choose 1 Forward. Increase its Power by 3000 until the end of the turn.',
      effect: Card_Chaos.onGame
    }
  ];

  Card_Chaos.prototype.skills = [
    {
      cost: {
        "super": 1,
        fire: 4,
        dull: true
      },
      name: 'Cosmo Memory',
      text: 'Deal 6000 damage to all Forwards opponent controls.',
      effect: Card_Chaos.CosmoMemory
    }
  ];

  Card_Chaos.prototype.onGame = function() {
    return this.game.choose({
      forward: 1
    }, function(forward) {
      return forward.power(3000);
    });
  };

  Card_Chaos.prototype.CosmoMemory = function() {
    var forward, forwards, _i, _len, _results;
    forwards = this.game.opponent().forwards();
    _results = [];
    for (_i = 0, _len = forwards.length; _i < _len; _i++) {
      forward = forwards[_i];
      _results.push(forward.damage(6000));
    }
    return _results;
  };

  return Card_Chaos;

})(Card);
