// Generated by CoffeeScript 1.6.3
var Card_Jecht_1, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Card_Jecht_1 = (function(_super) {
  __extends(Card_Jecht_1, _super);

  function Card_Jecht_1() {
    _ref = Card_Jecht_1.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Card_Jecht_1.prototype.name = 'Jecht';

  Card_Jecht_1.prototype.cost = {
    fire: 5
  };

  Card_Jecht_1.prototype.position = 'Forward';

  Card_Jecht_1.prototype.title = 'Guardian';

  Card_Jecht_1.prototype.serial = '1-011R';

  Card_Jecht_1.prototype.power = 8000;

  Card_Jecht_1.prototype.passives = [
    {
      text: 'Jecht gains 1000 Power for every Forward opponent control.',
      effect: Card_Jecht_1.getPower
    }
  ];

  Card_Jecht_1.prototype.skills = [
    {
      cost: {
        "super": 1,
        fire: 1,
        dark: 2,
        dull: true
      },
      name: 'Ultimate Jecht Shot',
      text: 'Choose 1 Forward. Break it.',
      effect: Card_Jecht_1.UltimateJechtShot
    }
  ];

  Card_Jecht_1.prototype.getPower = function() {
    return power + this.game.opponent().forwards().length * 1000;
  };

  Card_Jecht_1.prototype.UltimateJechtShot = function() {
    return this.game.choose({
      forward: 1
    }, function(forward) {
      return forward["break"]();
    });
  };

  return Card_Jecht_1;

})(Card);
