// Generated by CoffeeScript 1.6.3
var Card_Red_XIII_1, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Card_Red_XIII_1 = (function(_super) {
  __extends(Card_Red_XIII_1, _super);

  function Card_Red_XIII_1() {
    _ref = Card_Red_XIII_1.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Card_Red_XIII_1.prototype.name = 'Red XIII';

  Card_Red_XIII_1.prototype.cost = [
    {
      elt: "fire",
      nbr: 3
    }
  ];

  Card_Red_XIII_1.prototype.position = 'forward';

  Card_Red_XIII_1.prototype.title = 'Warrior';

  Card_Red_XIII_1.prototype.serial = '1-023R';

  Card_Red_XIII_1.prototype.power = 7000;

  Card_Red_XIII_1.prototype.abilities = [
    {
      text: 'When Red XIII enters the Field, choose 1 Forward. Increase its Power by 3000 until the end of the turn.',
      effect: Card_Red_XIII_1.onGame
    }, {
      cost: [
        {
          elt: "special",
          nbr: ""
        }, {
          elt: "fire",
          nbr: 4
        }, {
          elt: "dull",
          nbr: ""
        }
      ],
      name: 'Cosmo Memory',
      text: 'Deal 6000 damage to all Forwards opponent controls.',
      effect: Card_Red_XIII_1.CosmoMemory
    }
  ];

  Card_Red_XIII_1.prototype.onGame = function() {
    return this.game.choose({
      forward: 1
    }, function(forward) {
      return forward.power(3000);
    });
  };

  Card_Red_XIII_1.prototype.CosmoMemory = function() {
    var forward, forwards, _i, _len, _results;
    forwards = this.game.opponent().forwards();
    _results = [];
    for (_i = 0, _len = forwards.length; _i < _len; _i++) {
      forward = forwards[_i];
      _results.push(forward.damage(6000));
    }
    return _results;
  };

  return Card_Red_XIII_1;

})(Card);
