// Generated by CoffeeScript 1.6.3
var Card;

Card = (function() {
  function Card() {
    this.dulled = false;
  }

  Card.prototype.setPlayer = function(player) {
    this.player = player;
  };

  Card.prototype.setPlay = function(play) {
    this.play = play;
  };

  Card.prototype.dull = function() {
    return this.dulled = true;
  };

  Card.prototype.undull = function() {
    return this.dulled = false;
  };

  Card.prototype.discard = function() {
    var _ref;
    this.player.hand = _.without(this.player.hand, this);
    this.player.breaks.unshift(this);
    if ((_ref = this.cost[0].elt) !== 'light' && _ref !== 'dark') {
      return this.player.crystals[this.cost[0].elt] += 2;
    }
  };

  return Card;

})();
