// Generated by CoffeeScript 1.6.3
var Card;

Card = (function() {
  function Card() {
    this.dulled = false;
  }

  Card.prototype.setPlay = function(play) {
    this.play = play;
  };

  Card.prototype.dull = function() {
    return this.dulled = true;
  };

  Card.prototype.undull = function() {
    return this.dulled = false;
  };

  return Card;

})();
