// Generated by CoffeeScript 1.6.3
var Play;

Play = (function() {
  function Play(game) {
    var card, _i, _j, _len, _len1, _ref, _ref1;
    this.game = game;
    this.player = new Player('Player');
    this.player.deck = this.game.decks[0];
    _ref = this.player.deck.cards;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      card = _ref[_i];
      card.setPlayer(this.player);
      card.setPlay(this);
    }
    this.computer = new Computer_1('Computer');
    _ref1 = this.computer.deck.cards;
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      card = _ref1[_j];
      card.setPlayer(this.computer);
      card.setPlay(this);
    }
    this.current = this.player;
    this.opponent = this.computer;
    this.startPhase('reset');
    this.run();
  }

  Play.prototype.run = function() {
    var _this = this;
    return this.game.$timeout(function() {
      var _ref;
      _this.time--;
      if (_this.time <= 0) {
        switch (_this.phase) {
          case 'reset':
            _this.current.undullCards();
            _this.startPhase('draw');
            break;
          case 'draw':
            _this.current.draw();
            _this.startPhase('main1', 60);
            break;
          case 'main1':
            _this.startPhase('attack', 100);
            break;
          case 'attack':
            _this.startPhase('main2', 60);
            break;
          case 'main2':
            _this.startPhase('end');
            break;
          case 'end':
            _this.startPhase('reset');
            _ref = [_this.opponent, _this.current], _this.current = _ref[0], _this.opponent = _ref[1];
        }
      }
      return _this.run();
    }, 1000);
  };

  Play.prototype.startPhase = function(phase, time) {
    this.phase = phase;
    this.time = time != null ? time : 0;
  };

  Play.prototype.endPhase = function() {
    return this.time = 0;
  };

  return Play;

})();
