// Generated by CoffeeScript 1.6.3
var Play;

Play = (function() {
  function Play(game) {
    var card, _i, _j, _len, _len1, _ref, _ref1;
    this.game = game;
    this.player = new Player('Player', this);
    this.player.deck = this.game.decks[0];
    _ref = this.player.deck.cards;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      card = _ref[_i];
      card.setPlay(this);
    }
    this.opponent = new Opponent1('Computer', this);
    _ref1 = this.opponent.deck.cards;
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      card = _ref1[_j];
      card.setPlay(this);
    }
    this.current = this.player;
    this.startPhase('reset');
    this.run();
  }

  Play.prototype.run = function() {
    var _this = this;
    return this.game.$timeout(function() {
      _this.time--;
      if (_this.time <= 0) {
        switch (_this.phase) {
          case 'reset':
            _this.current.undullCards();
            _this.startPhase('draw', 0);
            break;
          case 'draw':
            _this.current.draw();
            _this.startPhase('main1', 60);
            break;
          case 'main1':
            _this.startPhase('attack', 100);
            break;
          case 'attack':
            _this.startPhase('main2', 60);
            break;
          case 'main2':
            _this.startPhase('end', 0);
            break;
          case 'end':
            _this.startPhase('waiting', -1);
            _this.current.finishTurn();
        }
      }
      return _this.run();
    }, 1000);
  };

  Play.prototype.startPhase = function(phase, time) {
    this.phase = phase;
    this.time = time != null ? time : 0;
  };

  return Play;

})();
